baseurl = "/"
languageCode = "es-es"
title = "magga"
theme = "hugo-xmin"
googleAnalytics = "UA-133551776-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"
    biblioteca = "/:sections/:title/"
    cantos = "/:sections/:title/"
    primeros-pasos = "/:sections/:title/"

[[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
[[menu.main]]
    name = "biblioteca"
    url = "/biblioteca/"
    weight = 2
[[menu.main]]
    name = "primeros pasos"
    url = "/primeros-pasos/"
    weight = 3
[[menu.main]]
    name = "cantos"
    url = "/cantos/"
    weight = 5
[[menu.main]]
    name = "magga traducciones"
    url = "/magga-traducciones/"
    weight = 5

[params]
    description = ""
    footer = "&copy; magga traducciones 2008 -- 2020"
