baseurl = "/"
languageCode = "es-es"
title = "magga"
theme = "hugo-xmin"
# googleAnalytics = "UA-133551776-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
[[menu.main]]
    name = "biblioteca"
    url = "/biblioteca/"
    weight = 2
[[menu.main]]
    name = "primeros pasos"
    url = "/primeros-pasos/"
    weight = 3
[[menu.main]]
    name = "magga traducciones"
    url = "/magga-traducciones/"
    weight = 4
[[menu.main]]
    name = "suscribirse"
    url = "/suscribirse/"
    weight = 5

[params]
    description = ""
    footer = "&copy; magga traducciones 2008 -- 2019 | [Twitter](https://twitter.com/magga_es)"
